# inspired by the "Night Owl" VSCode theme by Sarah Drasner

[ui]
fg-primary = "base-foreground"
fg-secondary = "comment"
selection-bg = "selection"
selection-fg = "base-foreground"
indicator-success = "accent-green"
indicator-error = "accent-red"
indicator-info = "accent-purple"
app-name = "accent-purple"

[panel]
active-bg = "base-background"
active-border = "accent-orange"
inactive-bg = "tab-inactive"
inactive-border = "badge-background"
active-input-border = "accent-cyan"

[popup]
border = "accent-cyan"
bg = "base-background"

[tab]
active = "accent-orange"
inactive = "comment"

[data]
boolean = "accent-red"
date = "accent-cyan"
key = "base-foreground"
number = "accent-orange"
object-id = "accent-cyan"
string = "accent-green"
punctuation = "comment"
mongo-operator = "accent-cyan"

[documents]
note = "comment"
search = "accent-blue"


[palette]
# Main Colors:
base-background = "#011627" # (Dark navy blue, primary editor background)
base-foreground = "#d6deeb" # (Light blue-grey, primary text color)
selection = "#1d3b53"       # (Muted blue, text selection)
accent-purple = "#c792ea"   # (Purple, used for keywords and control flow)
accent-green = "#c5e478"    # (Light green, used for strings and attributes)
accent-blue = "#82AAFF"     # (Light blue, used for functions and class names)
accent-orange = "#ffcb8b"   # (Light orange, used for classes and types)
accent-red = "#EF5350"      # (Red, used for errors and deletions)
accent-cyan = "#7fdbca"     # (Cyan, used for tags and operators)
comment = "#637777"

# UI Elements:
border = "#122d42"              # (Dark blue, used for focus and contrast borders)
input-background = "#0b253a"    # (Dark blue, form inputs)
badge-background = "#5f7e97"    # (Muted blue-grey)
tab-active = "#0b2942"          # (Dark blue, active tab)
tab-inactive = "#01111d"        # (Darker blue, inactive tabs)
