# Dracula spec:
# ------------
# Background Dark rgb(14, 20, 25)
# Background 		  rgb(40, 42, 54)
# Current Line 		rgb(68, 71, 90)
# Foreground 		  rgb(248, 248, 242)
# Comment 		    rgb(98, 114, 164)
# Cyan 		        rgb(139, 233, 253)
# Green 		      rgb(80, 250, 123)
# Orange 		      rgb(255, 184, 108)
# Pink 		        rgb(255, 121, 198)
# Purple 		      rgb(189, 147, 249)
# Red 		        rgb(255, 85, 85)
# Yellow 		      rgb(241, 250, 140)

[skin]
default = "rgb(248, 248, 242) none / gray(20) none"
tree = "rgb(98, 114, 164) None"
file = "rgb(248, 248, 242) None / gray(15) None"
directory = "rgb(189, 147, 249) None Bold"
exe = "rgb(255, 121, 198) None"
link = "rgb(255, 121, 198) None"
pruning = "gray(12) None Italic"
perm__ = "gray(5) None"
perm_r = "ansi(94) None"
perm_w = "ansi(132) None"
perm_x = "ansi(65) None"
owner = "ansi(138) None"
group = "ansi(131) None"
count = "ansi(136) rgb(14, 20, 25)"
dates = "ansi(66) None"
sparse = "ansi(214) None"
content_extract = "ansi(29) None"
content_match = "ansi(34) None"
git_branch = "ansi(229) None"
git_insertions = "ansi(28) None"
git_deletions = "ansi(160) None"
git_status_current = "gray(5) None"
git_status_modified = "ansi(28) None"
git_status_new = "ansi(94) None Bold"
git_status_ignored = "gray(17) None"
git_status_conflicted = "ansi(88) None"
git_status_other = "ansi(88) None"
selected_line = "None rgb(68, 71, 90) / None rgb(68, 71, 90)"
char_match = "rgb(241, 250, 140) None Bold"
file_error = "Red None"
flag_label = "gray(15) None"
flag_value = "rgb(255, 184, 108) None Bold"
input = "White None / gray(15) gray(2)"

status_error = "rgb(255, 121, 198) rgb(14, 20, 25)"
status_job = "ansi(220) gray(5)"
status_normal = "gray(20) rgb(14, 20, 25) / gray(2) gray(2)"
status_italic = "rgb(255, 184, 108) rgb(14, 20, 25) / gray(2) gray(2)"
status_bold = "rgb(255, 184, 108) rgb(14, 20, 25) Bold / gray(2) gray(2)"
status_code = "ansi(229) rgb(14, 20, 25) / gray(2) gray(2)"
status_ellipsis = "gray(19) gray(1) / gray(2) gray(2)"
purpose_normal = "gray(20) gray(2)"
purpose_italic = "ansi(178) gray(2)"
purpose_bold = "ansi(178) gray(2) Bold"
purpose_ellipsis = "gray(20) gray(2)"
scrollbar_track = "gray(7) None / gray(4) None"
scrollbar_thumb = "gray(22) None / gray(14) None"

help_paragraph = "gray(20) None"
help_bold = "rgb(255, 184, 108) None Bold"
help_italic = "rgb(241, 250, 140) None Italic"
help_code = "gray(21) rgb(14, 20, 25)"
help_headers = "rgb(255, 184, 108) None"
help_table_border = "rgb(98, 114, 164) None"

preview_title = "gray(23) None / gray(21) None"
preview = "gray(20) gray(1) / gray(18) gray(2)"
preview_line_number = "gray(12) rgb(14, 20, 25)"
preview_match = "None ansi(29)"
hex_null = "gray(11) None"
hex_ascii_graphic = "gray(18) None"
hex_ascii_whitespace = "ansi(143) None"
hex_ascii_other = "ansi(215) None"
hex_non_ascii = "ansi(167) None"
staging_area_title = "gray(22) None / gray(20) None"
mode_command_mark = "rgb(40, 42, 54) rgb(255, 121, 198) Bold"
good_to_bad_0 = "ansi(28)"
good_to_bad_1 = "ansi(29)"
good_to_bad_2 = "ansi(29)"
good_to_bad_3 = "ansi(29)"
good_to_bad_4 = "ansi(29)"
good_to_bad_5 = "ansi(100)"
good_to_bad_6 = "ansi(136)"
good_to_bad_7 = "ansi(172)"
good_to_bad_8 = "ansi(166)"
good_to_bad_9 = "ansi(196)"
