# Api config files, use `api_key` or `api_key_command` fields
# to set the api key for each api
# more details at https://github.com/efugier/smartcat#configuration

[openai]
url = "https://api.openai.com/v1/chat/completions"
default_model = "gpt-4"

[anthropic]
url = "https://api.anthropic.com/v1/messages"
default_model = "claude-3-5-sonnet-latest"
api_key_command = "cat ~/.anthropic"
version = "2023-06-01"

[ollama] 
url = "http://localhost:11434/api/chat"
default_model = "llama3.2"
timeout_seconds = 180

