# git abbreviations
abbr -a -- g    'git'
abbr -a -- gs   'git status -s'
abbr -a -- gsv  'git status'
abbr -a -- gl   'git lg'
abbr -a -- ga   'git add'
abbr -a -- gad  'git add .'
abbr -a -- gc   'git commit'
abbr -a -- gcm  'git commit -m'
abbr -a -- gca  'git commit --amend'
abbr -a -- gp   'git pull'
abbr -a -- gP   'git push'
abbr -a -- gri  'git rebase --interactive'
abbr -a -- grc  'git rebase --continue'
abbr -a -- gra  'git rebase --abort'
abbr -a -- gco  'git checkout'
abbr -a -- g..  'git checkout -'
abbr -a -- gsm  'git stash -um'
abbr -a -- gsl  'git stash list'
abbr -a -- gsp  'git stash pop'
abbr -a -- gsd  'git stash drop'
abbr -a -- gn   'git lg origin/(git branch --show-current)..head'
abbr -a -- gi   'git lg head..origin/(git branch --show-current)'
abbr -a -- gsu  'git submodule update --init --recursive'
abbr -a -- prc  'gh pr create -B'
abbr -a -- prv  'gh pr view -w'
