# jj abbreviations
abbr -a -- jab 'jj abandon'
abbr -a -- jb  'jj bookmark'
abbr -a -- jc  'jj commit'
abbr -a -- jd  'jj describe'
abbr -a -- jdi 'jj diff'
abbr -a -- je  'jj edit'
abbr -a -- jev 'jj evolve'
abbr -a -- jf  'jj fetch'
abbr -a -- ji  'jj inc'
abbr -a -- jl  'jj log'
abbr -a -- jn  'jj new'
abbr -a -- jo  'jj out'
abbr -a -- jp  'jj prep'
abbr -a -- jP  'jj push'
abbr -a -- jpp 'jj prep && jj push'
abbr -a -- jr  'jj rebase'
abbr -a -- jrs 'jj restore'
abbr -a -- js  'jj status'
abbr -a -- jsh 'jj show'
abbr -a -- jsp 'jj split'
abbr -a -- jS  'jj squash'
abbr -a -- ju  'jj undo'
abbr -a -- J   'jjui'

# alt-j to run `jj log` while preserving the command line
bind alt-j 'jj log; commandline -f repaint'
