[ui]
auto_refresh_interval = 3

[ui.colors]
selected = { bg = "#44475A" }

[[bindings]]
action = "revisions.inline_describe.accept"
scope = "revisions.inline_describe"
key = "ctrl+d"

[preview]
oplog_command = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  """jj op show $operation_id --color=always""",
]

revision_command = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  """jj diff -r $change_id --color=always | delta --pager 'less -R' --line-numbers""",
]

file_command = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  """jj diff -r $change_id $file --color=always | delta --pager 'less -R' --line-numbers""",
]
